@startuml

title Pileup Browser - Component Diagram

package "User Files" as Inputs {
  component Config
  component Alignment
  component Reference
}

package "Front End" {
    component [Terminal User\nInterface] as TUI
    component [Drawing Library] as Draw
    interface "User Console" as Cns
}

package "Input Handling" {
  component [Startup CLI] as CLI
  component [Pileup Engine] as Reader
}

package "Database Handling" {
component Pileup2SQL as P2S
database "SQLite\n" {
    [Pileup Table] as PT
}
component "Query API" as qa
}


Inputs -right-> CLI
CLI --> Reader
Reader -down-> P2S
P2S -down-> PT
PT -- qa
qa -- TUI
TUI -- Draw
TUI -- Cns

@enduml